s=input()
print("Is given String alphanumeric",s.isalnum())
print("Is given String alphabet",s.isalpha())
print("length of given String",len(s))
print("Is given String a title",s.istitle())
print(" ".join(s))
print("upper",s.upper())
print("lower",s.lower())
print("Is String in lower case",s.islower())
print("Is String in upper case",s.isupper())
print(s.split())
print("reverse",s[::-1])
